export const BUBBLE_SORT = "BUBBLE";
export const SELECTION_SORT = "SELECTION";
export const INSERTION_SORT = "INSERTION";
export const MERGE_SORT = "MERGE";
export const QUICK_SORT = "QUICK"

export const ALGORITHMS = [BUBBLE_SORT, SELECTION_SORT, INSERTION_SORT, MERGE_SORT, QUICK_SORT];